In [7]:
import os
import pandas as pd
import sqlite3

In [8]:
# Считываение и установка индексов для SQL файлов
dir = os.path.abspath(os.curdir).replace('pandas_graphs', 'data/').replace("\\", '/')
connect = sqlite3.connect(dir + 'weather_2012.sqlite')
weather_df = pd.read_sql('SELECT * from weather_2012 LIMIT 310', connect, index_col=['id', 'date_time'])
weather_df

                         temp
id  date_time
1   2012-01-01 00:00:00  -1.8
2   2012-01-01 01:00:00  -1.8
3   2012-01-01 02:00:00  -1.8
4   2012-01-01 03:00:00  -1.5
5   2012-01-01 04:00:00  -1.5
6   2012-01-01 05:00:00  -1.4
7   2012-01-01 06:00:00  -1.5
8   2012-01-01 07:00:00  -1.4
9   2012-01-01 08:00:00  -1.4
10  2012-01-01 09:00:00  -1.3
11  2012-01-01 10:00:00  -1.0
12  2012-01-01 11:00:00  -0.5
13  2012-01-01 12:00:00  -0.2
14  2012-01-01 13:00:00   0.2
15  2012-01-01 14:00:00   0.8
16  2012-01-01 15:00:00   1.8
17  2012-01-01 16:00:00   2.6
18  2012-01-01 17:00:00   3.0
19  2012-01-01 18:00:00   3.8
20  2012-01-01 19:00:00   3.1
21  2012-01-01 20:00:00   3.2
22  2012-01-01 21:00:00   4.0
23  2012-01-01 22:00:00   4.4
24  2012-01-01 23:00:00   5.3
25  2012-01-02 00:00:00   5.2
26  2012-01-02 01:00:00   4.6
27  2012-01-02 02:00:00   3.9
28  2012-01-02 03:00:00   3.7
29  2012-01-02 04:00:00   2.9
30  2012-01-02 05:00:00   2.6
...                       ...
71  2012-01-03 22:00:00 -17.1
72  2012-01-03 23:00:00 -17.3
73  2012-01-04 00:00:00 -17.5
74  2012-01-04 01:00:00 -17.9
75  2012-01-04 02:00:00 -18.1
76  2012-01-04 03:00:00 -18.5
77  2012-01-04 04:00:00 -18.5
78  2012-01-04 05:00:00 -18.6
79  2012-01-04 06:00:00 -18.5
80  2012-01-04 07:00:00 -18.2
81  2012-01-04 08:00:00 -17.8
82  2012-01-04 09:00:00 -16.8
83  2012-01-04 10:00:00 -15.2
84  2012-01-04 11:00:00 -14.2
85  2012-01-04 12:00:00 -13.7
86  2012-01-04 13:00:00 -12.4
87  2012-01-04 14:00:00 -11.3
88  2012-01-04 15:00:00 -10.2
89  2012-01-04 16:00:00  -9.4
90  2012-01-04 17:00:00  -8.9
91  2012-01-04 18:00:00  -8.9
92  2012-01-04 19:00:00  -8.4
93  2012-01-04 20:00:00  -7.8
94  2012-01-04 21:00:00  -7.6
95  2012-01-04 22:00:00  -9.5
96  2012-01-04 23:00:00  -9.6
97  2012-01-05 00:00:00  -8.8
98  2012-01-05 01:00:00  -7.5
99  2012-01-05 02:00:00  -5.4
100 2012-01-05 03:00:00  -5.0

[100 rows x 1 columns]

In [9]:
# Создаём файл test_db, считываем weather_2012 и если weather_2012 существует, очищаем test_db и записываем туда weather_2012
weather_df = pd.read_csv(dir + 'weather_2012.csv')
connect = sqlite3.connect(dir + 'test_db.sqlite')
connect.execute('DROP TABLE IF EXISTS weather_2012')
weather_df.to_sql('weather_2012', connect)

d:\python 3.7.2\lib\site-packages\pandas\core\generic.py:2130: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  dtype=dtype)

In [24]:
# Считываем ранее созданный файл и сортируем языком SQL
connect = sqlite3.connect('data/test_db.sqlite')
test1_df = pd.read_sql('SELECT * from weather_2012', connect)
test2_df = pd.read_sql('SELECT *from weather_2012 ORDER BY Weather', connect)
test2_df

,index,Date/Time,Temp (°C),Dew Point Temp (°C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
1,114,2012-01-05 18:00:00,-7.1,-14.4,56,11,25.0,100.71,Clear
2,115,2012-01-05 19:00:00,-9.2,-15.4,61,7,25.0,100.80,Clear
3,116,2012-01-05 20:00:00,-9.8,-15.7,62,9,25.0,100.83,Clear
4,117,2012-01-05 21:00:00,-9.0,-14.8,63,13,25.0,100.83,Clear
5,241,2012-01-11 01:00:00,-10.7,-17.8,56,17,25.0,101.49,Clear
6,242,2012-01-11 02:00:00,-12.0,-18.9,56,19,25.0,101.57,Clear
7,243,2012-01-11 03:00:00,-12.7,-19.4,57,19,25.0,101.64,Clear
8,244,2012-01-11 04:00:00,-13.4,-20.1,57,17,25.0,101.66,Clear
9,344,2012-01-15 08:00:00,-23.3,-28.5,62,7,24.1,102.45,Clear
10,351,2012-01-15 15:00:00,-15.4,-22.8,53,24,48.3,102.71,Clear
11,352,2012-01-15 16:00:00,-15.1,-22.8,52,24,48.3,102.79,Clear
12,353,2012-01-15 17:00:00,-16.2,-23.2,55,15,25.0,102.85,Clear
13,354,2012-01-15 18:00:00,-16.3,-22.9,57,17,25.0,102.89,Clear
14,355,2012-01-15 19:00:00,-16.3,-22.7,58,20,25.0,102.94,Clear
15,356,2012-01-15 20:00:00,-16.7,-22.4,61,17,25.0,102.98,Clear
16,357,2012-01-15 21:00:00,-16.9,-22.2,63,15,25.0,103.02,Clear
17,358,2012-01-15 22:00:00,-16.9,-21.7,66,17,25.0,103.07,Clear
18,359,2012-01-15 23:00:00,-16.9,-21.4,68,15,25.0,103.09,Clear
19,360,2012-01-16 00:00:00,-17.1,-21.9,66,15,25.0,103.09,Clear
20,361,2012-01-16 01:00:00,-17.8,-22.7,65,6,25.0,103.05,Clear
21,362,2012-01-16 02:00:00,-18.5,-23.0,68,6,25.0,103.08,Clear
22,363,2012-01-16 03:00:00,-19.2,-23.8,67,6,25.0,103.07,Clear
23,364,2012-01-16 04:00:00,-18.7,-23.5,66,0,25.0,103.05,Clear
24,365,2012-01-16 05:00:00,-19.1,-23.3,69,0,25.0,103.02,Clear
25,366,2012-01-16 06:00:00,-18.7,-23.2,68,0,25.0,103.01,Clear
26,425,2012-01-18 17:00:00,-11.3,-18.8,54,26,48.3,101.54,Clear
27,426,2012-01-18 18:00:00,-12.0,-18.2,60,22,25.0,101.67,Clear
28,427,2012-01-18 19:00:00,-12.7,-18.7,61,22,25.0,101.78,Clear
29,428,2012-01-18 20:00:00,-13.4,-19.2,62,17,25.0,101.83,Clear
...,...,...,...,...,...,...,...,...,...
8754,8428,2012-12-17 04:00:00,-3.0,-4.1,92,24,6.4,100.91,"Snow,Ice Pellets"
8755,8429,2012-12-17 05:00:00,-3.0,-4.2,91,24,8.0,100.89,"Snow,Ice Pellets"
8756,8430,2012-12-17 06:00:00,-2.1,-3.2,92,19,8.0,100.88,"Snow,Ice Pellets"
8757,4456,2012-07-04 16:00:00,26.7,20.1,67,15,24.1,99.84,Thunderstorms
8758,4729,2012-07-16 01:00:00,21.6,19.4,87,0,25.0,100.62,Thunderstorms
8759,3582,2012-05-29 06:00:00,10.9,9.0,88,9,2.4,100.26,"Thunderstorms,Heavy Rain Showers"
8760,4758,2012-07-17 06:00:00,19.6,18.5,93,15,3.2,100.01,"Thunderstorms,Moderate Rain Showers,Fog"
8761,3500,2012-05-25 20:00:00,21.3,18.3,83,13,16.1,100.83,"Thunderstorms,Rain"
8762,4913,2012-07-23 17:00:00,19.4,18.2,93,4,24.1,100.24,"Thunderstorms,Rain"
8763,4914,2012-07-23 18:00:00,20.6,19.1,91,30,19.3,100.19,"Thunderstorms,Rain"
8764,3580,2012-05-29 04:00:00,11.4,7.0,74,30,24.1,100.34,"Thunderstorms,Rain Showers"
8765,3581,2012-05-29 05:00:00,11.0,8.9,87,15,12.9,100.14,"Thunderstorms,Rain Showers"
8766,3592,2012-05-29 16:00:00,21.0,17.5,80,15,9.7,99.75,"Thunderstorms,Rain Showers"
8767,3593,2012-05-29 17:00:00,20.7,17.4,81,13,12.9,99.84,"Thunderstorms,Rain Showers"
8768,4457,2012-07-04 17:00:00,21.6,20.0,91,11,24.1,100.02,"Thunderstorms,Rain Showers"
8769,4719,2012-07-15 15:00:00,22.7,20.9,90,24,12.9,100.92,"Thunderstorms,Rain Showers"
8770,4766,2012-07-17 14:00:00,25.5,23.1,87,17,6.4,99.65,"Thunderstorms,Rain Showers"
8771,4768,2012-07-17 16:00:00,23.8,21.7,88,24,16.1,99.81,"Thunderstorms,Rain Showers"
8772,4917,2012-07-23 21:00:00,18.1,17.7,98,11,6.4,100.27,"Thunderstorms,Rain Showers"
8773,4918,2012-07-23 22:00:00,18.7,18.0,96,7,6.4,100.04,"Thunderstorms,Rain Showers"
8774,5109,2012-07-31 21:00:00,22.8,18.8,78,13,25.0,100.65,"Thunderstorms,Rain Showers"
8775,5226,2012-08-05 18:00:00,25.0,22.0,83,22,19.3,100.28,"Thunderstorms,Rain Showers"
8776,5369,2012-08-11 17:00:00,20.2,19.5,96,32,12.9,100.58,"Thunderstorms,Rain Showers"
8777,5842,2012-08-31 10:00:00,19.7,17.8,89,20,24.1,100.54,"Thunderstorms,Rain Showers"
8778,6028,2012-09-08 04:00:00,21.9,15.8,68,17,25.0,99.85,"Thunderstorms,Rain Showers"
8779,6188,2012-09-14 20:00:00,16.5,15.8,96,22,16.1,101.06,"Thunderstorms,Rain Showers"
8780,4323,2012-06-29 03:00:00,19.5,16.1,81,7,9.7,99.71,"Thunderstorms,Rain Showers,Fog"
8781,4761,2012-07-17 09:00:00,22.9,21.3,91,17,9.7,99.84,"Thunderstorms,Rain Showers,Fog"
8782,5108,2012-07-31 20:00:00,22.4,18.7,80,35,9.7,100.64,"Thunderstorms,Rain Showers,Fog"
8783,4757,2012-07-17 05:00:00,20.6,18.6,88,19,4.8,100.08,"Thunderstorms,Rain,Fog"